nama = input("Masukkan nama anda : ")
panda = input("asal daerah anda : ")
ttl = input("Masukkan tempat tanggal lahir anda : ")
makanan_favorit = input("Masukkan makanan favorit anda : ")
cita_cita = input("cita-cita anda : ")
email = input( "Masukkan email anda : ")
print("Nama :", nama)
print("Panda :", panda)
print("TTL :", ttl)
print("Makanan Favorit :", makanan_favorit)
print("Cita-cita :",cita_cita)
print("Email :",email)